/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.herumi.bls;

public interface BlsConstants {
  public final static int BN254 = 0;
  public final static int BLS12_381 = 5;
  public final static int ETH_MODE_OLD = 0;
  public final static int ETH_MODE_LATEST = 3;
  public final static int MSG_SIZE = 32;
}
